version: "3"

services:
  nginx:
    image: makevoid/instrument-nginx
    build:
      context: nginx
    depends_on:
      - app
      - app_ws
    ports:
      - 80:80
      - 81:81
  app:
    image: makevoid/redis-app-sample1:latest
    build:
      context: app
    environment:
      RACK_ENV: production
    depends_on:
      - redis
    ports:
      - 3000
  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6379
  app_ws:
    image: makevoid/redis-app-ws-sample1:latest
    build:
      context: app_ws
    environment:
      RACK_ENV: production
    ports:
      - 3001:3001
